## Just a theme
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: There's a cat in the milky way
description: Clinical haematology, tumour immunology, astrophotography and cats. But now it's just a reservation app...
